"use strict";
console.log("Hey,Abu Hurairah,I have started learning TYPESCRIPT.");
var Name = "Ahmad";
console.log("My Name is " + Name);
var num1 = 2;
var num2 = 4;
var num3 = 6;
var num4 = 8;
var num5 = 10;
var num6 = 12;
var num7 = 14;
var num8 = 16;
var num9 = 18;
var num10 = 20;
var sum = (num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10);
var sub = (num1 - num2 - num3 - num4 - num5 - num6 - num7 - num8 - num9 - num10);
var div = (num10 / num5);
var mul = (num1 * num2 * num3 * num4 * num5 * num6 * num7 * num8 * num9 * num10);
console.log("Total sum is =" + sum);
console.log("Total sub is =" + sub);
console.log("Total muliple is =" + mul);
console.log("The divide is =" + div);
