console.log("Hey,Abu Hurairah,I have started learning TYPESCRIPT.");
var Name:string = "Ahmad";
console.log("My Name is " + Name);
var num1:number = 2;
var num2:number = 4;
var num3:number = 6;
var num4:number = 8;
var num5:number = 10;
var num6:number = 12;
var num7:number = 14;
var num8:number = 16;
var num9:number = 18;
var num10:number = 20;
var sum:number = (num1+num2+num3+num4+num5+num6+num7+num8+num9+num10);
var sub:number = (num1-num2-num3-num4-num5-num6-num7-num8-num9-num10);
var div:number = (num10/num5);
var mul:number = (num1*num2*num3*num4*num5*num6*num7*num8*num9*num10);
console.log("Total sum is =" + sum);
console.log("Total sub is =" + sub);
console.log("Total muliple is =" + mul);
console.log("The divide is =" + div);
console.log("My first Typerscript Program");